#!/usr/bin/env python3
"""Dev bot main loop — Python Agent SDK version."""

from __future__ import annotations

import argparse
import asyncio
import contextlib
import json
import logging
import os
import shutil
import signal
import subprocess
import sys
import time
import uuid
from pathlib import Path

from dotenv import load_dotenv
from filelock import FileLock, Timeout
from prometheus_client import start_http_server

from . import idle_reminder
from .agent import push_status, run_cycle
from .config import (
    ALLOWED_TOOLS,
    DEFAULT_PROVIDER_ID,
    DEFAULT_RUNTIME_ID,
    Config,
    InstanceConfig,
    load_config,
    load_instance_config,
    load_mcp_servers,
    resolve_active_envs,
    resolve_cycle_model,
    resolve_workflow_dir,
    sanitize_env,
    validate_instance_config,
    validate_manifest,
    validate_runtime_provider_selection,
)
from .costs import record_cost
from .log import bind, clear, setup_logging
from .merge import apply_merged_config, install_skills
from .metrics import (
    CONFIG_SYNC_TOTAL,
    CYCLE_DURATION_SECONDS,
    CYCLE_TIMEOUT_TOTAL,
    DISK_FREE_MB,
    PREFLIGHT_CONSECUTIVE_ERRORS,
    PREFLIGHT_OUTCOME_TOTAL,
    WORK_TYPE_TOTAL,
)
from .preflight import run_preflight
from .transcripts import post_orphan_cycle, record_transcript

SCRIPT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = SCRIPT_DIR / "data"


def _resolve_path(p: str) -> str:
    """Resolve a path that may be relative to SCRIPT_DIR, ~, or absolute."""
    path = Path(p).expanduser()
    if not path.is_absolute():
        path = SCRIPT_DIR / path
    return str(path.resolve())


def setup_git(script_dir: Path) -> None:
    """Generate per-platform .gitconfig files with includeIf.

    Reads GH_USER_NAME/GH_USER_EMAIL and GL_USER_NAME/GL_USER_EMAIL
    from env. Each platform gets its own identity and signing key.
    Sets GIT_CONFIG_GLOBAL so all repos use this config.
    """
    gh_name = os.environ.get("GH_USER_NAME")
    gh_email = os.environ.get("GH_USER_EMAIL")
    gl_name = os.environ.get("GL_USER_NAME")
    gl_email = os.environ.get("GL_USER_EMAIL")
    git_proxy_host = os.environ.get("GIT_AUTH_PROXY_HOST")
    gl_ca_cert_file = os.environ.get("GITLAB_CA_CERT_FILE", "").strip()

    if not gh_name and not gl_name:
        return

    config_path = script_dir / ".gitconfig"
    gh_config = script_dir / ".gitconfig-gh"
    gl_config = script_dir / ".gitconfig-gl"

    for path, name, email, key_env in [
        (gh_config, gh_name, gh_email, "GH_GPG_SIGNING_KEY"),
        (gl_config, gl_name, gl_email, "GL_GPG_SIGNING_KEY"),
    ]:
        lines = ["# Auto-generated by bot/run.py", "[user]"]
        if name:
            lines.append(f"\tname = {name}")
        if email:
            lines.append(f"\temail = {email}")
        signing_key = os.environ.get(key_env) or os.environ.get("GPG_SIGNING_KEY")
        if signing_key:
            lines.append(f"\tsigningkey = {signing_key}")
        path.write_text("\n".join(lines) + "\n")

    lines = [
        "# Auto-generated by bot/run.py — do not edit manually",
        '[includeIf "hasconfig:remote.*.url:https://github.com/**"]',
        f"\tpath = {gh_config}",
        '[includeIf "hasconfig:remote.*.url:https://gitlab.cee.redhat.com/**"]',
        f"\tpath = {gl_config}",
        "[commit]",
        "\tgpgsign = true",
        "[gpg]",
        "\tformat = openpgp",
    ]
    if git_proxy_host:
        lines.extend(
            [
                f'[url "http://{git_proxy_host}:8447/github.com/"]',
                "\tinsteadOf = https://github.com/",
                f'[url "http://{git_proxy_host}:8447/gitlab.cee.redhat.com/"]',
                "\tinsteadOf = https://gitlab.cee.redhat.com/",
            ]
        )
    else:
        lines.extend(
            [
                '[credential "https://github.com"]',
                "\thelper = !/usr/local/bin/gh auth git-credential",
                '[credential "https://gitlab.cee.redhat.com"]',
                "\thelper = !/usr/local/bin/glab credential-helper",
            ]
        )

    if gl_ca_cert_file:
        lines.extend(
            [
                '[http "https://gitlab.cee.redhat.com/"]',
                f"\tsslCAInfo = {gl_ca_cert_file}",
                "\tsslVerify = true",
            ]
        )

    config_path.write_text("\n".join(lines) + "\n")
    os.environ["GIT_CONFIG_GLOBAL"] = str(config_path)


REMOTE_CONFIG_DIR = DATA_DIR / "remote-config"


def sync_config_repo(label: str) -> tuple[Path | None, Path | None]:
    """Clone or pull BOT_CONFIG_REPO.

    Returns (profile_agent_dir, shared_agent_dir).
    shared_agent_dir is the sibling ``shared/agent/`` directory if it exists.
    """
    logger = logging.getLogger(__name__)
    repo_url = os.environ.get("BOT_CONFIG_REPO")
    if not repo_url:
        return None, None

    config_dir = REMOTE_CONFIG_DIR
    try:
        if (config_dir / ".git").exists():
            r = subprocess.run(
                ["git", "-C", str(config_dir), "pull", "--ff-only"],
                capture_output=True,
                timeout=30,
                check=False,
            )
            if r.returncode != 0:
                logger.warning(
                    "git pull failed (rc=%d): %s",
                    r.returncode,
                    r.stderr.decode().strip(),
                )
                CONFIG_SYNC_TOTAL.labels(label, "pull_failed").inc()
        else:
            config_dir.parent.mkdir(parents=True, exist_ok=True)
            r = subprocess.run(
                ["git", "clone", "--depth", "1", repo_url, str(config_dir)],
                capture_output=True,
                timeout=60,
                check=False,
            )
            if r.returncode != 0:
                logger.warning(
                    "git clone failed (rc=%d): %s",
                    r.returncode,
                    r.stderr.decode().strip(),
                )
                CONFIG_SYNC_TOTAL.labels(label, "clone_failed").inc()
                return None, None
    except subprocess.TimeoutExpired:
        logger.warning("Config repo sync timed out — using built-in config")
        CONFIG_SYNC_TOTAL.labels(label, "timeout").inc()
        return None, None
    except Exception as exc:
        logger.warning("Config repo sync failed: %s — using built-in config", exc)
        CONFIG_SYNC_TOTAL.labels(label, "error").inc()
        return None, None

    sub = os.environ.get("BOT_CONFIG_PATH", "rehor-config")
    profile_dir = config_dir / sub
    agent_dir = profile_dir / "agent"
    if not agent_dir.is_dir():
        logger.warning("Config repo has no %s/agent/ dir — using built-in config", sub)
        CONFIG_SYNC_TOTAL.labels(label, "no_agent_dir").inc()
        return None, None

    shared_agent_dir = None
    shared_dir = profile_dir.parent / "shared" / "agent"
    if shared_dir.is_dir():
        shared_agent_dir = shared_dir
        logger.info("Multi-profile: shared config at %s", shared_dir)

    CONFIG_SYNC_TOTAL.labels(label, "ok").inc()
    return agent_dir, shared_agent_dir


SLEEP_SIGNAL_FILE = DATA_DIR / "cycle-sleep.json"
LOW_DISK_THRESHOLD_MB = 512


def _try_slack_digest() -> None:
    from .slack_digest import try_slack_digest

    try_slack_digest()


def _write_sleep_signal(seconds: int, reason: str) -> None:
    """Write a sleep signal file for the runner to read after the cycle."""
    SLEEP_SIGNAL_FILE.parent.mkdir(parents=True, exist_ok=True)
    SLEEP_SIGNAL_FILE.write_text(json.dumps({"recommended_sleep": seconds, "reason": reason}))


def _read_sleep_signal(config: Config) -> int:
    """Read sleep duration from skill-written signal file.

    Skills write data/cycle-sleep.json with {"recommended_sleep": N, "reason": "..."}.
    No file = standard interval (work was done). File is always deleted after reading.
    """
    logger = logging.getLogger(__name__)
    sleep_seconds = config.interval

    if SLEEP_SIGNAL_FILE.exists():
        try:
            sig = json.loads(SLEEP_SIGNAL_FILE.read_text())
            sleep_seconds = sig.get("recommended_sleep", config.interval)
            reason = sig.get("reason", "")
            logger.info("Sleep signal: %ds (%s)", sleep_seconds, reason)
        except Exception:
            logger.warning("Bad sleep signal file, using default %ds", config.interval)
        finally:
            SLEEP_SIGNAL_FILE.unlink(missing_ok=True)
    else:
        logger.info("No sleep signal, using default %ds", config.interval)

    logger.info("Sleeping for %ds...", sleep_seconds)
    time.sleep(sleep_seconds)
    return sleep_seconds


def assemble_claude_md(
    script_dir: Path,
    instance_config: InstanceConfig | None = None,
    remote_agent_dir: Path | None = None,
    shared_agent_dir: Path | None = None,
) -> None:
    """Concatenate core + shared + workflow preset CLAUDE.md into project root.

    Layer order: core → shared → workflow → instance.

    Supports instance CLAUDE.md via claude_md_strategy:
      replace — core + shared + instance CLAUDE.md (skip workflow)
      append  — core + shared + workflow + instance CLAUDE.md
      ignore  — core + shared + workflow only (default)
    """
    logger = logging.getLogger(__name__)
    presets = script_dir / "presets"
    core = presets / "core" / "CLAUDE.md"

    workflow = instance_config.workflow if instance_config else os.environ.get("BOT_WORKFLOW_PRESET", "jira-sprint")
    strategy = instance_config.claude_md_strategy if instance_config else "ignore"

    if not core.is_file():
        logger.warning("Core CLAUDE.md not found at %s — skipping assembly", core)
        return

    parts = [core.read_text()]

    shared_md = shared_agent_dir / "CLAUDE.md" if shared_agent_dir else None
    if shared_md is not None and shared_md.is_file():
        parts.append(shared_md.read_text())
        logger.info("CLAUDE.md: included shared layer from %s", shared_md)

    instance_md = remote_agent_dir / "CLAUDE.md" if remote_agent_dir else None
    has_instance_md = instance_md is not None and instance_md.is_file()

    if strategy == "replace" and has_instance_md:
        parts.append(instance_md.read_text())
        logger.info("CLAUDE.md strategy=replace — using instance CLAUDE.md instead of workflow")
    else:
        wf_path = resolve_workflow_dir(script_dir, workflow, remote_agent_dir) / "CLAUDE.md"
        if wf_path.is_file():
            parts.append(wf_path.read_text())
        else:
            logger.warning("Workflow CLAUDE.md not found at %s — using core only", wf_path)
        if strategy == "append" and has_instance_md:
            parts.append(instance_md.read_text())
            logger.info("CLAUDE.md strategy=append — appended instance CLAUDE.md")

    output = script_dir / "CLAUDE.md"
    output.write_text("".join(parts))
    logger.info("Assembled CLAUDE.md from core + %s (%d bytes)", workflow, output.stat().st_size)


def cleanup_between_cycles(script_dir: Path) -> None:
    """Free disk space between cycles if below threshold."""
    logger = logging.getLogger(__name__)

    SLEEP_SIGNAL_FILE.unlink(missing_ok=True)

    try:
        usage = shutil.disk_usage(str(script_dir))
        free_mb = usage.free // (1024 * 1024)
    except OSError:
        return
    DISK_FREE_MB.set(free_mb)

    if free_mb >= LOW_DISK_THRESHOLD_MB:
        logger.info("Disk OK: %dM free (threshold %dM)", free_mb, LOW_DISK_THRESHOLD_MB)
        return

    logger.warning(
        "Low disk: %dM free (threshold %dM) — cleaning up",
        free_mb,
        LOW_DISK_THRESHOLD_MB,
    )

    for name, cmd in [
        ("Go build cache", ["go", "clean", "-cache"]),
        ("Go mod cache", ["go", "clean", "-modcache"]),
        ("npm cache", ["npm", "cache", "clean", "--force"]),
    ]:
        try:
            subprocess.run(cmd, capture_output=True, timeout=30)
            logger.info("Cleaned %s", name)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

    repos_dir = script_dir / "repos"
    if repos_dir.exists():
        for repo in repos_dir.iterdir():
            if (repo / ".git").is_dir():
                with contextlib.suppress(subprocess.TimeoutExpired, FileNotFoundError):
                    subprocess.run(
                        ["git", "gc", "--auto", "--quiet"],
                        cwd=str(repo),
                        capture_output=True,
                        timeout=60,
                    )

    try:
        usage = shutil.disk_usage(str(script_dir))
        free_mb = usage.free // (1024 * 1024)
        DISK_FREE_MB.set(free_mb)
        logger.info("Cleanup done. Free space: %dM", free_mb)
    except OSError:
        pass


def handle_cycle_timeout(timeout_seconds: int, label: str) -> tuple[None, None]:
    """Log timeout and warn about lost cost data. Returns (None, None) for result, ctx."""
    logger = logging.getLogger(__name__)
    logger.error(
        "Cycle timed out after %ds — skipping to next cycle",
        timeout_seconds,
    )
    logger.warning("Cost data for timed-out cycle lost (SDK does not expose partial usage)")
    CYCLE_TIMEOUT_TOTAL.labels(label).inc()
    return None, None


def validate_python_runner_selection(instance_config: InstanceConfig) -> None:
    """Fail closed instead of silently ignoring a coordinator selection.

    The legacy Python loop owns only the Claude/Vertex path. The TypeScript
    coordinator consumes non-default selections; an old image must not run an
    OpenCode config through the Claude SDK by accident.
    """
    logger = logging.getLogger(__name__)
    errors = validate_runtime_provider_selection(instance_config.runtime, instance_config.provider)
    if errors:
        for error in errors:
            logger.error("FATAL: %s", error)
        sys.exit(1)
    if (instance_config.runtime, instance_config.provider) != (
        DEFAULT_RUNTIME_ID,
        DEFAULT_PROVIDER_ID,
    ):
        logger.error(
            "Runtime/provider selection %s/%s requires the TypeScript coordinator; "
            "the Python runner supports only %s/%s",
            instance_config.runtime,
            instance_config.provider,
            DEFAULT_RUNTIME_ID,
            DEFAULT_PROVIDER_ID,
        )
        sys.exit(1)


def main() -> None:
    # Load .env before anything else so MCP servers get the credentials
    load_dotenv(SCRIPT_DIR / ".env")

    # Set up git identity from env vars (no-op if not configured)
    setup_git(SCRIPT_DIR)

    parser = argparse.ArgumentParser(description="Dev bot agent loop")
    parser.add_argument(
        "--label",
        required=True,
        help="Primary Jira label (e.g. hcc-ai-framework)",
    )
    parser.add_argument(
        "--instance-id",
        default=os.environ.get("BOT_INSTANCE_ID", ""),
        help="Bot instance ID for multi-instance isolation (default: $BOT_INSTANCE_ID)",
    )
    args = parser.parse_args()

    if not args.instance_id:
        parser.error("--instance-id is required (or set BOT_INSTANCE_ID env var)")

    setup_logging()
    logger = logging.getLogger(__name__)

    try:
        config = load_config(SCRIPT_DIR)
        mcp_servers = load_mcp_servers(SCRIPT_DIR)

        # Initial config sync + instance config load (before validation so
        # instance.yaml can override the workflow preset)
        initial_agent_dir, initial_shared_dir = sync_config_repo(args.label)
        if initial_shared_dir:
            apply_merged_config(SCRIPT_DIR, initial_shared_dir)
        if initial_agent_dir:
            apply_merged_config(SCRIPT_DIR, initial_agent_dir)
        instance_config = load_instance_config(initial_agent_dir)
        install_skills(
            SCRIPT_DIR,
            resolve_workflow_dir(SCRIPT_DIR, instance_config.workflow, initial_agent_dir),
            resolve_active_envs(SCRIPT_DIR, instance_config),
        )

        validate_manifest(
            SCRIPT_DIR,
            instance_config.workflow,
            mcp_servers,
            initial_agent_dir,
            model_tiers=config.model_tiers,
        )
        validate_instance_config(SCRIPT_DIR, instance_config, initial_agent_dir)
        validate_python_runner_selection(instance_config)

        # Remove secrets from env so Bash subprocesses can't leak them.
        # MCP servers already have resolved values. gh/glab use config files.
        sanitize_env()
        logger.info("Sanitized environment — secrets removed from env vars.")

        # Lock file — prevent concurrent runs
        lock = FileLock(DATA_DIR / ".lock", timeout=0)
        try:
            lock.acquire()
        except Timeout:
            logger.error("Another instance is running. Exiting.")
            sys.exit(1)

        def shutdown(sig, frame):
            logger.info("Shutting down.")
            lock.release()
            sys.exit(0)

        signal.signal(signal.SIGINT, shutdown)
        signal.signal(signal.SIGTERM, shutdown)

        start_http_server(9091)
        logger.info("Metrics server listening on :9091")

        instance_id = args.instance_id or None
        logger.info(
            "Dev bot started. Label: %s. Instance: %s. Provider: Vertex AI. Active interval: %ds. Idle interval: %ds.",
            args.label,
            instance_id or "(none)",
            config.interval,
            config.idle_interval,
        )

        consecutive_preflight_errors = 0

        try:
            while True:
                # run_id for log correlation across this loop iteration (roadmap §9 will persist)
                run_id = str(uuid.uuid4())
                clear()
                bind(run_id=run_id)
                try:
                    _try_slack_digest()

                    remote_agent_dir, shared_agent_dir = sync_config_repo(args.label)
                    if shared_agent_dir:
                        apply_merged_config(SCRIPT_DIR, shared_agent_dir)
                    if remote_agent_dir:
                        apply_merged_config(SCRIPT_DIR, remote_agent_dir)

                    instance_config = load_instance_config(remote_agent_dir)
                    validate_python_runner_selection(instance_config)
                    install_skills(
                        SCRIPT_DIR,
                        resolve_workflow_dir(SCRIPT_DIR, instance_config.workflow, remote_agent_dir),
                        resolve_active_envs(SCRIPT_DIR, instance_config),
                    )
                    assemble_claude_md(SCRIPT_DIR, instance_config, remote_agent_dir, shared_agent_dir)

                    # --- Pre-flight: gather data before starting AI session ---
                    preflight_result = run_preflight(
                        SCRIPT_DIR, instance_config.workflow, remote_agent_dir, instance_id
                    )

                    preflight_prompt = None
                    if preflight_result is not None:
                        if preflight_result.action == "error":
                            consecutive_preflight_errors += 1
                            logger.error("Preflight error (consecutive: %d)", consecutive_preflight_errors)
                            PREFLIGHT_OUTCOME_TOTAL.labels(args.label, "error").inc()
                            PREFLIGHT_CONSECUTIVE_ERRORS.labels(args.label).set(consecutive_preflight_errors)
                            WORK_TYPE_TOTAL.labels(args.label, "error").inc()
                            post_orphan_cycle(
                                instance_id or args.label,
                                "error",
                                preflight_result.transcript,
                                input_prompt=preflight_result.transcript,
                            )
                            push_status("error", "Preflight failed — check bot.log", instance_id=instance_id)
                            error_sleep = min(config.interval * (2**consecutive_preflight_errors), 300)
                            _write_sleep_signal(error_sleep, "preflight_error")
                            _read_sleep_signal(config)
                            cleanup_between_cycles(SCRIPT_DIR)
                            continue

                        if preflight_result.action == "skip":
                            consecutive_preflight_errors = 0
                            logger.info("Preflight skip — no session needed")
                            PREFLIGHT_OUTCOME_TOTAL.labels(args.label, "skip").inc()
                            PREFLIGHT_CONSECUTIVE_ERRORS.labels(args.label).set(0)
                            WORK_TYPE_TOTAL.labels(args.label, "idle").inc()
                            post_orphan_cycle(
                                instance_id or args.label,
                                "idle",
                                preflight_result.transcript,
                                input_prompt=preflight_result.transcript,
                            )
                            push_status("idle", "No work found. Sleeping...", instance_id=instance_id)
                            idle_reminder.on_preflight_skip(
                                instance_id or args.label,
                                idle_cycle_limit=instance_config.idle_cycle_limit,
                                cooldown_seconds=config.idle_reminder_cooldown_seconds,
                            )
                            _write_sleep_signal(config.idle_interval, "preflight_skip")
                            _read_sleep_signal(config)
                            cleanup_between_cycles(SCRIPT_DIR)
                            continue

                        # action == "start"
                        consecutive_preflight_errors = 0
                        PREFLIGHT_OUTCOME_TOTAL.labels(args.label, "start").inc()
                        PREFLIGHT_CONSECUTIVE_ERRORS.labels(args.label).set(0)
                        idle_reminder.on_preflight_start(instance_id or args.label)
                        preflight_prompt = preflight_result.prompt
                        logger.info("Preflight start — launching session with pre-fetched data")

                    cycle_model = resolve_cycle_model(SCRIPT_DIR, instance_config, config, remote_agent_dir)
                    bind(model=cycle_model)
                    logger.info("Running agent cycle with model %s...", cycle_model)

                    cycle_start = time.monotonic()
                    try:
                        result, ctx = asyncio.run(
                            asyncio.wait_for(
                                run_cycle(
                                    label=args.label,
                                    config=config,
                                    mcp_servers=mcp_servers,
                                    allowed_tools=ALLOWED_TOOLS,
                                    cwd=str(SCRIPT_DIR),
                                    instance_id=instance_id,
                                    preflight_prompt=preflight_prompt,
                                    model=cycle_model,
                                ),
                                timeout=config.cycle_timeout,
                            )
                        )
                    except TimeoutError:
                        result, ctx = handle_cycle_timeout(config.cycle_timeout, args.label)
                    cycle_duration = time.monotonic() - cycle_start
                    work_type = (ctx.work_type if ctx else None) or "unknown"
                    CYCLE_DURATION_SECONDS.labels(args.label, work_type).observe(cycle_duration)

                    if result is not None:
                        bind(
                            task_key=ctx.jira_key if ctx else None,
                            cost=result.total_cost_usd if result.total_cost_usd is not None else None,
                        )
                        record_cost(
                            costs_file=DATA_DIR / "costs.jsonl",
                            label=args.label,
                            result=result,
                            ctx=ctx,
                            instance_id=instance_id,
                            workflow=instance_config.workflow,
                        )
                        record_transcript(
                            label=args.label,
                            result=result,
                            ctx=ctx,
                            cwd=str(SCRIPT_DIR),
                            instance_id=instance_id,
                            input_prompt=preflight_prompt,
                        )
                    else:
                        if ctx and ctx.jira_key:
                            bind(task_key=ctx.jira_key)
                        logger.warning("Cycle produced no result")

                    _read_sleep_signal(config)

                    cleanup_between_cycles(SCRIPT_DIR)
                except Exception:
                    logger.exception("Cycle failed with unhandled exception")
                    error_sleep = min(config.interval, 300)
                    _write_sleep_signal(error_sleep, "cycle_exception")
                    _read_sleep_signal(config)
                    cleanup_between_cycles(SCRIPT_DIR)
                finally:
                    clear()
        finally:
            lock.release()
    except Exception:
        logger.exception("Fatal error during bot execution")
        sys.exit(1)
